### ISSUE TITLE
Difficulty creating new fragments for a hasManyFragments attribute

### ISSUE THREAD

**Issue by ghost** [adopted-ember-addons/ember-data-model-fragments#36]
Hi There,

I know this is not the best place for "usage" issues, but with the module still being in its infancy - I figured I would have a much better chance of a response here and i'm really stumped!!

I am trying to essentially replicate the "addresses" part of the example in the readme except using Ember CLI and names appropriate for my App. I have no trouble loading data into the fragments and later accessing it, but I am having a lot of difficulty creating new fragments into a hasManyFragments attribute.

When following the "addresses" part of the example in my App, to create a new fragment, I receive a `Cannot read property 'createFragment' of null` error when attempting to call createFragment on my hasManyFragments attribute. When using the Ember Chrome inspector, my hasManyFragments attribute is indeed set to null. Should this be null?

``` javascript
// /models/collection.js
import DS from 'ember-data';

export default DS.Model.extend({
    rev: DS.attr('string'),
    type: DS.attr('string'),
    name: DS.attr('string'),
    products: DS.hasManyFragments('collection-products'),
    meta: DS.hasOneFragment('collection-meta'),
    credentials: DS.hasManyFragments()
});
```

``` javascript
// /models/collection-products.js
import DS from 'ember-data';

export default DS.ModelFragment.extend({
  productId: DS.attr('string'),
  productTitle: DS.attr('string'),
  order: DS.attr('string')
});
```

``` javascript
// /routes/collection.js
import Ember from 'ember';

export default Ember.Route.extend({
  model: function(params) {
      var collection = this.store.createRecord('collection');
      return collection;
  }
});
```

``` javascript
// /controllers/collection.js
import Ember from 'ember';

export default Ember.Controller.extend({
  actions: {
    addToCollection: function(product){
      var products = this.get('model.products');

      products.createFragment('collection-products', {productId: product.get('id'), productTitle: product.get('title')});
      console.log('Added product');
    }
  }
});
```

Appreciate any help :sweat_smile:

**Comment by knownasilya** [comment]
@slindberg also would love this in 1.0
