### ISSUE TITLE
Put addon up for adoption?

### ISSUE THREAD

**Issue by patocallaghan** [adopted-ember-addons/ember-data-model-fragments#382]
Considering some of the trouble encountered in https://github.com/lytics/ember-data-model-fragments/pull/381 with finding an admin who can help manage this addon, would it make sense to put this addon up for adoption to the [adopted-ember-addons](https://github.com/adopted-ember-addons) org?

When an original owner no longer has time to maintain the addon, there is a place where the addon can be "put up for adoption." [Melanie Sumner](https://github.com/MelSumner) has created [adopted-ember-addons](https://github.com/adopted-ember-addons). See the dedicated [#ember-adopted-addons](https://discord.com/channels/480462759797063690/525367494400278538) channel in the Ember Discord.

Would you consider allowing us to adopt ember-data-model-fragments so that the addon may continue to provide useful service to the community?

/cc @jakesjews @araddon

**Comment by jakesjews** [comment]
That is cool with me. I haven't had to much time to work on this so it would probably be for the best.

**Comment by patocallaghan** [comment]
@jakesjews cool, there are a list of things that we'd need done to make it happen (see below).  I think ultimately we need to get final sign off from someone at Lytics?

### [Addon Transfer Checklist](https://github.com/adopted-ember-addons/program-guidelines)
These are the things that need to done to transfer your addon:
* [ ] To get your addon adopted, please ping one of the adopted-ember-addons org owners (`@Melanie#1618`, `@Alon#3707`, or `@knownasilya#9990`) in the Ember Discord chat in the #adopted-ember-addons channel and let them know what repository you'd like to transfer.
* [ ] Once they are aware, complete the Addon Transfer checklist (below).
   * [ ] Update the repository field of the package.json to point to the new location.
   * [ ] If any demo URL or homepage is referenced, it should be updated. At the very least, file an issue on the repository so the adopter can fix.
   * [ ] Ensure Release practices are documented.
   * [ ] Add at least one of the adopted-ember-addons org owners (melsumner, alonbukai, or knownasilya) to the maintainers of the package on npm. Make sure they have all admin permissions. Remove other maintainers, if reasonable.
* [ ] After the checklist is complete, transfer the repository to one of them here on GitHub.
* [ ] The org owner is then responsible to transfer the addon to this org (Adopted Ember Addons).

**Comment by DingoEatingFuzz** [comment]
Hi, former Lytics employee here. I can get ahold of Lytics and see if they'd be willing to transfer ownership.

**Comment by markhayden** [comment]
Hi, current Lytics employee here. I'll have a couple of conversations in the morning to make sure there isn't any reason we wouldn't be open to the adoption and then make sure things start moving from there. Thanks!

**Comment by patocallaghan** [comment]
@markhayden any updates?

**Comment by jakesjews** [comment]
@patocallaghan is a fork an option?

**Comment by patocallaghan** [comment]
@markhayden sorry for an additional ping, is there any update? It appears we are currently blocked from [making any contributions to this repo](https://github.com/lytics/ember-data-model-fragments/pull/385).

@jakesjews that's not ideal and IMHO should only be a last resort. While we could fork the repo, we'd still need to be able to publish the npm package.

**Comment by sarahyablok** [comment]
@patocallaghan @jakesjews Hi, also current Lytics employee. We'll be working on the steps to get this addon up for adoption during this sprint so expect updates sometime in the next two weeks.

**Comment by markhayden** [comment]
@jakesjews do you have access to the NPM for this addon? one of the required steps for adoption is: 

```
Add at least one of the adopted-ember-addons org owners (melsumner, alonbukai, or knownasilya) to the maintainers of the package on npm. Make sure they have all admin permissions. Remove other maintainers, if reasonable.
``` 

we are having trouble tracking down anyone with access on NPM. thanks!

**Comment by DingoEatingFuzz** [comment]
@markhayden I still have npm access.

**Comment by DingoEatingFuzz** [comment]
They have all been added as maintainers.

**Comment by jakesjews** [comment]
I do still have NPM access

**Comment by markhayden** [comment]
transfer complete. woohoo!

**Comment by knownasilya** [comment]
There are a few people with write permissions on the repo, do you want to stay on or be removed?

@workmanw @jakesjews @devinus

**Comment by jakesjews** [comment]
I'm probably not going to be contributing very much so you can remove me

**Comment by patocallaghan** [comment]
Oh awesome, that turned around quite quickly 😃 Thanks everyone for all your help!

**Comment by GuillaumeCisco** [comment]
Who is adopting it?

**Comment by patocallaghan** [comment]
@GuillaumeCisco the [Adopted Ember Addons](https://github.com/adopted-ember-addons) org. I'll aim to get a new beta release out in the next day or two.

**Comment by knownasilya** [comment]
Still haven't gotten the npm invite email. Not sure what's going on.

**Comment by patocallaghan** [comment]
Ah okay, I'll reopen the issue until we get the npm invite /cc @DingoEatingFuzz @jakesjews @markhayden

**Comment by DingoEatingFuzz** [comment]
@knownasilya and I have been working through this. It seems to be an npm issue that may have been resolved? If not I'll reach out to npm.
