### ISSUE TITLE
Idea: nested definitions without extra files

### ISSUE THREAD

**Issue by knownasilya** [adopted-ember-addons/ember-data-model-fragments#387]
Currently we have a pretty big setup, but it's hard to navigate since each little object is in it's own file. Would love to be able to see it all as a tree in one place.

**Comment by patocallaghan** [comment]
@knownasilya Funnily enough the oldest open issue on the repo is a proposal for this exact thing 😃 https://github.com/adopted-ember-addons/ember-data-model-fragments/issues/16

**Comment by knownasilya** [comment]
I'll close this and comment there 😸
