### ISSUE TITLE
Changelog is outdated

### ISSUE THREAD

**Issue by ro0gr** [adopted-ember-addons/ember-data-model-fragments#420]
Seems changelog.md is outdated. At the moment it points to the v5.0.0-beta.1, while we have v5.0.0-beta.3 published. At the same time GH release notes seems to be up to date(I believe formed manually, which is fine, but....).

Should we remove the changelog.md in order to avoid confusion and difference with GH releases changelog. Or should it be automated somehow?

**Comment by knownasilya** [comment]
It should be automated. The adopted addons org has a guidelines repo that goes over this.

**Comment by patocallaghan** [comment]
Yep we should be following the release process from https://github.com/adopted-ember-addons/program-guidelines#release-process.
